#!/bin/bash
# Arkeo Sentinel One-Click Installer
# Generated by the Arkeo Marketplace wizard
# Usage: curl -s <url> | bash
#
# This script:
# 1. Installs Docker (if not present)
# 2. Writes your sentinel config
# 3. Writes your metadata.json
# 4. Sets up nginx + free SSL (optional)
# 5. Starts the sentinel
# 6. Verifies everything works

set -euo pipefail

# ── Configuration (injected by wizard) ────────────────────────
PROVIDER_PUBKEY="{{PROVIDER_PUBKEY}}"
SOURCE_CHAIN="{{SOURCE_CHAIN}}"
HUB_URI="{{HUB_URI}}"
HUB_FALLBACKS="{{HUB_FALLBACKS}}"
SERVICE_NAME="{{SERVICE_NAME}}"
RPC_URL="{{RPC_URL}}"
FREE_RATE_LIMIT="{{FREE_RATE_LIMIT}}"
CONTRACT_RATE_LIMIT="{{CONTRACT_RATE_LIMIT}}"
MONIKER="{{MONIKER}}"
DESCRIPTION="{{DESCRIPTION}}"
LOCATION="{{LOCATION}}"
DOMAIN="{{DOMAIN}}"
# ──────────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'

echo ""
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║     🛡️  Arkeo Sentinel Installer         ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Provider:  ${BOLD}${MONIKER}${NC}"
echo -e "  Service:   ${SERVICE_NAME}"
echo -e "  Node RPC:  ${RPC_URL}"
if [ -n "$DOMAIN" ]; then
echo -e "  Domain:    ${DOMAIN}"
fi
echo ""

# ── Step 1: Check/Install Docker ─────────────────────────────
echo -e "${CYAN}[1/5]${NC} Checking Docker..."
if command -v docker &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Docker already installed"
else
    echo -e "  ${YELLOW}→${NC} Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo -e "  ${GREEN}✓${NC} Docker installed and started"
fi

# ── Step 2: Write config ─────────────────────────────────────
echo -e "${CYAN}[2/5]${NC} Writing sentinel config..."
mkdir -p ~/.arkeo

cat > ~/.arkeo/config.yaml << 'SENTINEL_CONFIG'
# Arkeo Sentinel Configuration
# Generated by Arkeo Marketplace Installer

host: 0.0.0.0
port: 3636
provider_pubkey: ${PROVIDER_PUBKEY}
source_chain: ${SOURCE_CHAIN}
hub_provider_uri: ${HUB_URI}
SENTINEL_CONFIG

# Use envsubst-style replacement since heredoc won't expand
sed -i "s|\${PROVIDER_PUBKEY}|${PROVIDER_PUBKEY}|g" ~/.arkeo/config.yaml
sed -i "s|\${SOURCE_CHAIN}|${SOURCE_CHAIN}|g" ~/.arkeo/config.yaml
sed -i "s|\${HUB_URI}|${HUB_URI}|g" ~/.arkeo/config.yaml

# Add fallbacks if present
if [ -n "$HUB_FALLBACKS" ]; then
    echo "hub_provider_fallbacks:" >> ~/.arkeo/config.yaml
    IFS=',' read -ra FALLBACK_ARRAY <<< "$HUB_FALLBACKS"
    for fb in "${FALLBACK_ARRAY[@]}"; do
        echo "  - $fb" >> ~/.arkeo/config.yaml
    done
fi

cat >> ~/.arkeo/config.yaml << EOF
event_stream_host: wss://rpc-seed.arkeo.network/websocket
free_rate_limit: ${FREE_RATE_LIMIT}
free_rate_limit_duration: 1m
contract_rate_limit: ${CONTRACT_RATE_LIMIT}
contract_rate_limit_duration: 1m
claims_enabled: true
claim_check_interval: 30m

services:
  - name: ${SERVICE_NAME}
    rpc_url: ${RPC_URL}
EOF

echo -e "  ${GREEN}✓${NC} Config saved to ~/.arkeo/config.yaml"

# Write metadata.json
cat > ~/.arkeo/metadata.json << EOF
{
  "moniker": "${MONIKER}",
  "description": "${DESCRIPTION}",
  "location": "${LOCATION}",
  "website": "",
  "sentinel_url": "${DOMAIN:+https://$DOMAIN}",
  "port": "3636",
  "source_chain": "${SOURCE_CHAIN}",
  "provider_pubkey": "${PROVIDER_PUBKEY}",
  "free_tier_rate_limit": ${FREE_RATE_LIMIT},
  "services": [{"name": "${SERVICE_NAME}", "type": "rpc"}]
}
EOF
echo -e "  ${GREEN}✓${NC} Metadata saved to ~/.arkeo/metadata.json"

# ── Step 3: Set up HTTPS (if domain provided) ────────────────
if [ -n "$DOMAIN" ]; then
    echo -e "${CYAN}[3/5]${NC} Setting up HTTPS for ${DOMAIN}..."
    
    # Install nginx and certbot if needed
    if ! command -v nginx &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq nginx certbot python3-certbot-nginx > /dev/null 2>&1
        echo -e "  ${GREEN}✓${NC} Nginx + Certbot installed"
    else
        if ! command -v certbot &>/dev/null; then
            apt-get update -qq && apt-get install -y -qq certbot python3-certbot-nginx > /dev/null 2>&1
        fi
        echo -e "  ${GREEN}✓${NC} Nginx already installed"
    fi
    
    # Write nginx config
    cat > /etc/nginx/sites-available/arkeo-sentinel << EOF
server {
    server_name ${DOMAIN};
    
    location / {
        proxy_pass http://127.0.0.1:3636/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Content-Type, Authorization, X-Arkauth' always;
        if (\$request_method = OPTIONS) { return 204; }
    }
    
    listen 80;
}
EOF
    
    ln -sf /etc/nginx/sites-available/arkeo-sentinel /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
    nginx -t > /dev/null 2>&1 && systemctl reload nginx
    
    # Get SSL cert
    echo -e "  ${YELLOW}→${NC} Getting SSL certificate (this may take a minute)..."
    certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email --redirect > /dev/null 2>&1 && \
        echo -e "  ${GREEN}✓${NC} HTTPS configured with auto-renewal" || \
        echo -e "  ${YELLOW}⚠${NC} SSL setup failed — sentinel will work on HTTP. Run 'certbot --nginx -d ${DOMAIN}' manually."
else
    echo -e "${CYAN}[3/5]${NC} Skipping HTTPS (no domain provided)"
    echo -e "  ${YELLOW}ℹ${NC} Sentinel will be available at http://YOUR_IP:3636"
    echo -e "  ${YELLOW}ℹ${NC} Add a domain later for HTTPS (recommended)"
fi

# ── Step 4: Start sentinel ────────────────────────────────────
echo -e "${CYAN}[4/5]${NC} Starting sentinel..."

# Stop any existing sentinel
docker stop arkeo-sentinel 2>/dev/null || true
docker rm arkeo-sentinel 2>/dev/null || true

docker run -d --name arkeo-sentinel \
    -p 3636:3636 \
    -v ~/.arkeo:/root/.arkeo \
    --restart unless-stopped \
    ghcr.io/arkeonetwork/sentinel:latest > /dev/null 2>&1

# Wait for startup
sleep 3

if docker ps | grep -q arkeo-sentinel; then
    echo -e "  ${GREEN}✓${NC} Sentinel is running"
else
    echo -e "  ${RED}✗${NC} Sentinel failed to start. Check logs with: docker logs arkeo-sentinel"
    exit 1
fi

# ── Step 5: Verify ────────────────────────────────────────────
echo -e "${CYAN}[5/5]${NC} Verifying..."

# Test local
HEALTH=$(curl -s --max-time 5 http://localhost:3636/metadata.json 2>/dev/null)
if echo "$HEALTH" | grep -q "moniker"; then
    echo -e "  ${GREEN}✓${NC} Sentinel responding locally"
else
    echo -e "  ${YELLOW}⚠${NC} Sentinel not responding yet — it may need a few more seconds to start"
fi

# Test public (if domain)
if [ -n "$DOMAIN" ]; then
    sleep 2
    PUBLIC=$(curl -s --max-time 10 "https://${DOMAIN}/metadata.json" 2>/dev/null)
    if echo "$PUBLIC" | grep -q "moniker"; then
        echo -e "  ${GREEN}✓${NC} Public HTTPS endpoint working"
    else
        echo -e "  ${YELLOW}⚠${NC} Public endpoint not responding yet — DNS may need a few minutes to propagate"
    fi
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║     🚀  Sentinel is Live!                ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
if [ -n "$DOMAIN" ]; then
echo -e "  Your sentinel: ${BOLD}https://${DOMAIN}${NC}"
else
echo -e "  Your sentinel: ${BOLD}http://$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_IP'):3636${NC}"
fi
echo -e "  Config:        ~/.arkeo/config.yaml"
echo -e "  Metadata:      ~/.arkeo/metadata.json"
echo -e "  Logs:          docker logs -f arkeo-sentinel"
echo ""
echo -e "  ${CYAN}Go back to the marketplace wizard and click 'Test My Sentinel'${NC}"
echo ""
